    call npm install @types/marked --save-dev
    call npm install @types/node --save-dev
    call npm install angular2-router-loader --save-dev
    call npm install angular2-template-loader --save-dev
    call npm install awesome-typescript-loader --save-dev
    call npm install copy-webpack-plugin --save-dev
    call npm install css-loader --save-dev
    call npm install extract-text-webpack-plugin --save-dev
    call npm install file-loader --save-dev
    call npm install html-loader --save-dev
    call npm install html-webpack-plugin --save-dev
    call npm install null-loader --save-dev
    call npm install raw-loader --save-dev
    call npm install rimraf --save-dev
    call npm install style-loader --save-dev
    call npm install typescript --save-dev
    call npm install webpack --save-dev
    call npm install webpack-dev-server --save-dev
    call npm install webpack-merge --save-dev

